version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      # Sync all files and folders except node_modules
      - .:/usr/src/app
      - /usr/src/app/node_modules # Keep container's node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # If you need to specify a host for Metro, uncomment the following
      # - REACT_NATIVE_PACKAGER_HOSTNAME=$(ipconfig getifaddr en0 || echo 127.0.0.1) 